### PR TITLE
making compatible with sos.

### PR DESCRIPTION
**Pull request by nfultz**

### CODE REVIEW

**Comment by nfultz** [comment]
Here's an example session:
```
> library(sos)
> library(docstring)
> ???bayesfactor
found 80 matches;  retrieving 4 pages
2 3 4 
Downloaded 80 links in 10 packages.
> square <- function(x){
+ 
+     #' Square a number
+     #'
+     #' Calculates the square of the input
+     #'
+     #' @param x the input to be squared
+ 
+     return(x^2)
+ }
> 
> ?square
> ?cat
```

**Comment by Dasonk** [comment]
Interesting.  It's failing the travis builds in the check phase though. It's giving:

```
checking whether the package can be loaded with stated dependencies ... WARNING
Error : .onAttach failed in attachNamespace() for 'docstring', details:
  call: get("?", parent.env(parent.env(.GlobalEnv)))
  error: object '?' not found
Error: package or namespace load failed for ‘docstring’
Execution halted
```

**Comment by nfultz** [comment]
Fixed by changing `get` to `get0`.

**Comment by Dasonk** [comment]
I've been quite busy lately and haven't had much time to play around with this.  I'll give it some attention hopefully in the next week or so.

**Pull request closed without merging**
